on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # - name: Test repo
      #   uses: carlos8v/jest-evaluator-action-test@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request
        with:
          message: 'Test'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
