on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Test repo
        id: evaluator
        uses: carlos8v/jest-evaluator-action@v1

      - name: Output result
        run: echo "The time was ${{ steps.evaluator.outputs.result }}"

      # - name: Comment PR
      #   uses: thollander/actions-comment-pull-request
      #   with:
      #     message: ${{ steps.evaluator.outputs.result }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
