on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Test repo
        id: evaluator
        uses: carlos8v/jest-evaluator-action@v1.1

      - name: Output result
        run: echo "The result was ${{ steps.evaluator.outputs.result }}"
